### ISSUE TITLE
fail to train

### ISSUE THREAD

**Issue by tachoi** [ashawkey/nerf2mesh#111]
**using this command:**
         "python main.py data/nerf_synthetic/lego/ --workspace trial_syn_lego/ -O --bound 1 --scale 0.8 --dt_gamma 0 --stage 0 --lambda_tv 1e-8"

**and get error as following:**
       KeyError: 'Percentage'
      Exception ignored in: <function tqdm.__del__ at 0x7dce6acd4720>
     Traceback (most recent call last):
     File "/home/simsys/anaconda3/envs/nerf2mesh/lib/python3.11/site-packages/tqdm/std.py", line 1148, in __del__
    self.close()
    File "/home/simsys/anaconda3/envs/nerf2mesh/lib/python3.11/site-packages/tqdm/std.py", line 1277, in close
    if self.last_print_t < self.start_t + self.delay:
       ^^^^^^^^^^^^^^^^^
**AttributeError: 'tqdm' object has no attribute 'last_print_t'**

**Comment by ZhuoranCool** [comment]
same problem. Is there any solution?

**Comment by tachoi** [comment]
Just commnet out, but other problem is occurred

-----Original Message-----

**Comment by Helena2007** [comment]
Try upgrading tqdm
