### ISSUE TITLE
ValueError: string is not a file: trial_custom/mesh_stage0/mesh_4.ply

### ISSUE THREAD

**Issue by nangongliufeng** [ashawkey/nerf2mesh#35]
Thanks for this very great work, how can this problem be solved please？
Traceback (most recent call last):
  File "main.py", line 159, in <module>
    model = NeRFNetwork(opt)
  File "/root/nerf2mesh/nerf/network.py", line 38, in __init__
    super().__init__(opt)
  File "/root/nerf2mesh/nerf/renderer.py", line 121, in __init__
    mesh = trimesh.load(os.path.join(self.opt.workspace, 'mesh_stage0', f'mesh_{cas}.ply'), force='mesh', skip_material=True, process=False)
  File "/root/miniconda3/envs/nerf2mesh/lib/python3.8/site-packages/trimesh/exchange/load.py", line 116, in load
    ) = parse_file_args(file_obj=file_obj,
  File "/root/miniconda3/envs/nerf2mesh/lib/python3.8/site-packages/trimesh/exchange/load.py", line 630, in parse_file_args
    raise ValueError('string is not a file: {}'.format(file_obj))
ValueError: string is not a file: trial_custom/mesh_stage0/mesh_4.ply

**Comment by LearnToStick** [comment]
i have a same error!

**Comment by nangongliufeng** [comment]
> 
If it is solved, please let me know how to solve it, thank you!

**Comment by nangongliufeng** [comment]
> i have a same error!
If it is solved, please let me know how to solve it, thank you!

**Comment by nangongliufeng** [comment]
@LearnToStick If it is solved, please let me know how to solve it, thank you!

**Comment by nangongliufeng** [comment]
> i have a same error!
adjust this parameter“--bound”

**Comment by nangongliufeng** [comment]
@LearnToStick adjust this parameter“--bound”

**Comment by Seiano** [comment]
@nangongliufeng  how to do adjust this parameter“--bound”?
