### ISSUE TITLE
Running on WSL?

### ISSUE THREAD

**Issue by jurrejelle** [ashawkey/nerf2mesh#39]
Hello, I'm trying to run this on WSL, running ubuntu

Running the first stage, I get
(pasting full output since I'm not sure if the warnings are relevant)
```
ubuntu@DESKTOP-CVF0MI9:/mnt/c/Users/jurre/Desktop/School/Minor/NeRF/nerf2mesh$ python main.py data/nerf_synthetic/lego/ --workspace trial_syn_lego/ -O --bound 1 --scale 0.8 --dt_gamma 0 --stage 0 --lambda_tv 1e-8
Warning:
Unable to load the following plugins:

        libio_e57.so: libio_e57.so does not seem to be a Qt Plugin.

Cannot load library /home/ubuntu/.local/lib/python3.8/site-packages/pymeshlab/lib/plugins/libio_e57.so: (/lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0)

Loading train data: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 58.13it/s]
[INFO] max_epoch 300, eval every 60, save every 6.
[INFO] Trainer: ngp_stage0 | 2023-05-05_10-58-04 | cuda | fp16 | trial_syn_lego/
[INFO] #parameters: 18367240
Namespace(H=1000, O=True, W=1000, adaptive_num_rays=True, background='random', bound=1.0, camera_traj='', ckpt='latest', clean_min_d=5, clean_min_f=8, color_space='srgb', contract=False, cuda_ray=True, data_format='nerf',
decimate_target=300000.0, density_thresh=10, diffuse_only=False, diffuse_step=1000, downscale=1, dt_gamma=0.0, enable_cam_center=False, enable_cam_near_far=False, enable_dense_depth=False, enable_offset_nerf_grad=False,
enable_sparse_depth=False, env_reso=256, fovy=50, fp16=True, grid_size=128, gui=False, ind_dim=0, ind_num=500, iters=30000, lambda_density=0, lambda_depth=0.1, lambda_edgelen=0, lambda_eikonal=0.1, lambda_entropy=0,
lambda_lap=0.001, lambda_lpips=0, lambda_mask=0.1, lambda_normal=0, lambda_offsets=0.1, lambda_rgb=1, lambda_specular=1e-05, lambda_tv=1e-08, lr=0.01, lr_vert=0.0001, mark_untrained=True, max_ray_batch=4096, max_spp=1,
max_steps=1024, mcubes_reso=512, mesh='', mesh_visibility_culling=True, min_near=0.05, n_ckpt=50, n_eval=5, num_points=262144, num_rays=4096, offset=[0, 0, 0], patch_size=1, path='data/nerf_synthetic/lego/', pos_gradient_boost=1,
preload=True, radius=5, random_image_batch=True, refine=True, refine_decimate_ratio=0.1, refine_remesh_size=0.02, refine_size=0.01, refine_steps=[3000, 6000, 9000, 12000, 15000, 21000], refine_steps_ratio=[0.1, 0.2, 0.3, 0.4, 0.5,
0.7], scale=0.8, sdf=False, seed=0, ssaa=2, stage=0, tcnn=False, test=False, test_no_mesh=False, test_no_video=False, texture_size=4096, train_split='train', trainable_density_grid=False, update_extra_interval=16, vis_pose=False,
visibility_mask_dilation=5, wo_smooth=False, workspace='trial_syn_lego/')
NeRFNetwork(
  (encoder): GridEncoder: input_dim=3 num_levels=16 level_dim=1 resolution=16 -> 2048 per_level_scale=1.3819 params=(6119864, 1) gridtype=hash align_corners=False interpolation=linear
  (sigma_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=19, out_features=32, bias=False)
      (1): Linear(in_features=32, out_features=1, bias=False)
    )
  )
  (encoder_color): GridEncoder: input_dim=3 num_levels=16 level_dim=2 resolution=16 -> 2048 per_level_scale=1.3819 params=(6119864, 2) gridtype=hash align_corners=False interpolation=linear
  (color_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=35, out_features=64, bias=False)
      (1): Linear(in_features=64, out_features=64, bias=False)
      (2): Linear(in_features=64, out_features=6, bias=False)
    )
  )
  (specular_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=6, out_features=32, bias=False)
      (1): Linear(in_features=32, out_features=3, bias=False)
    )
  )
)
[INFO] Loading latest checkpoint ...
[INFO] Latest checkpoint is trial_syn_lego/checkpoints/ngp_stage0_ep0300.pth
[INFO] loaded model.
[INFO] loaded EMA.
[INFO] load at epoch 300, global step 30000
[INFO] loaded optimizer.
[INFO] loaded scheduler.
[INFO] loaded scaler.
Loading val data: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 57.05it/s]
[mark untrained grid] 0 from 2097152
[INFO] training takes 0.000001 minutes.
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off]
/home/ubuntu/.local/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/ubuntu/.local/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/ubuntu/.local/lib/python3.8/site-packages/lpips/weights/v0.1/vgg.pth
++> Evaluate at epoch 300 ...
loss=0.000251 (0.000316): : 100% 100/100 [00:22<00:00,  4.44it/s]
PSNR = 35.362388
SSIM = 0.977125
LPIPS (vgg) = 0.029383
++> Evaluate epoch 300 Finished, loss = 0.000316
Loading test data: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:05<00:00, 39.96it/s]
++> Evaluate at epoch 300 ...
loss=0.000279 (0.000435): : 100% 200/200 [00:45<00:00,  4.37it/s]
PSNR = 34.270256
SSIM = 0.974770
LPIPS (vgg) = 0.032933
++> Evaluate epoch 300 Finished, loss = 0.000435
==> Start Test, save results to trial_syn_lego/results
100% 200/200 [00:18<00:00, 10.92it/s]==> Finished Test.
100% 200/200 [00:20<00:00,  9.67it/s]
==> Saving mesh to trial_syn_lego/mesh_stage0
[F glutil.cpp:332] eglGetDisplay() failed
Aborted
```

I guess this makes sense, since my WSL does not have a display, but I didn't think a display would be needed for a program like this?
What could I do to mitigate this? I'm not planning on running linux locally, nor do I have any linux machines laying around. I'm not sure how smooth a VM would be with GPU passthrough and the headaches that would come with it. Is it possible to run this without any display attached?

**Comment by ashawkey** [comment]
@jurrejelle Hi, the program doesn't require a display. This usually means OpenGL is not correctly installed, which is needed for nvdiffrast. Sorry that WSL is not tested or supported.

**Comment by jurrejelle** [comment]
I seem to have gotten it to work! It seemed like the problem under WSL for me was the `dr.RasterizeGLContext` calls in renderer.py. I have replaced those with `dr.RasterizeCudaContext`, and now it seems to work. This is a shot in the dark after seeing https://github.com/NVlabs/nvdiffrast/issues/92 which had similar error messages, and I'm not 100% sure this will give similar results, but as of now the program finished. Will update if the results aren't as I expected but this seems to work.

**Comment by ashawkey** [comment]
I remember the max resolution supported by the Cuda context is 2048, while by default we use 4096 and super-sampling to 8192 for better texture. You may need to use smaller texture resolution and disable `ssaa`, although the texture quality may drop.

**Comment by jurrejelle** [comment]
Ah, lovely. I was already looking into that, since just setting the resolution to 2048 didn't work, but disabling ssaa might resolve that. Will reply if I get it working :) 
(and later, if I get it working with the GL context on WSL, I'll also include it here for future people trying to run it on WSL)

**Comment by jurrejelle** [comment]
Alright, I've ran
`python main.py data/nerf_synthetic/lego/ --workspace trial_syn_lego/ -O --bound 1 --scale 0.8 --dt_gamma 0 --stage 0 --texture_size 2048 --ssaa 1 --lambda_tv 1e-8`

and am now trying to run 
`python main.py data/nerf_synthetic/lego/ --workspace trial_syn_lego/ -O --bound 1 --scale 0.8 --dt_gamma 0 --stage 1 --texture_size 2048 --ssaa 1`
However, it's giving an error of 
```python main.py data/nerf_synthetic/lego/ --workspace trial_syn_lego/ -O --bound 1 --scale 0.8 --dt_gamma 0 --stage 1 --texture_size 2048 --ssaa 1
Warning:
Unable to load the following plugins:

        libio_e57.so: libio_e57.so does not seem to be a Qt Plugin.

Cannot load library /home/ubuntu/.local/lib/python3.8/site-packages/pymeshlab/lib/plugins/libio_e57.so: (/lib/x86_64-linux-gnu/libp11-kit.so.0: undefined symbol: ffi_type_pointer, version LIBFFI_BASE_7.0)

[INFO] loaded cascade 0 mesh: (150854, 3), (300000, 3)
Loading train data: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 58.83it/s]
[INFO] max_epoch 300, eval every 60, save every 6.
[INFO] Trainer: ngp_stage1 | 2023-05-05_14-35-16 | cuda | fp16 | trial_syn_lego/
[INFO] #parameters: 18819802
Namespace(H=1000, O=True, W=1000, adaptive_num_rays=True, background='random', bound=1.0, camera_traj='', ckpt='latest', clean_min_d=5, clean_min_f=8, color_space='srgb', contract=False, cuda_ray=True,
data_format='nerf', decimate_target=300000.0, density_thresh=10, diffuse_only=False, diffuse_step=1000, downscale=1, dt_gamma=0.0, enable_cam_center=False, enable_cam_near_far=False, enable_dense_depth=False,
enable_offset_nerf_grad=False, enable_sparse_depth=False, env_reso=256, fovy=50, fp16=True, grid_size=128, gui=False, ind_dim=0, ind_num=500, iters=30000, lambda_density=0, lambda_depth=0.1, lambda_edgelen=0,
lambda_eikonal=0.1, lambda_entropy=0, lambda_lap=0.001, lambda_lpips=0, lambda_mask=0.1, lambda_normal=0, lambda_offsets=0.1, lambda_rgb=1, lambda_specular=1e-05, lambda_tv=1e-08, lr=0.01, lr_vert=0.0001,
mark_untrained=True, max_ray_batch=4096, max_spp=1, max_steps=1024, mcubes_reso=512, mesh='', mesh_visibility_culling=True, min_near=0.05, n_ckpt=50, n_eval=5, num_points=262144, num_rays=4096, offset=[0, 0, 0],
patch_size=1, path='data/nerf_synthetic/lego/', pos_gradient_boost=1, preload=True, radius=5, random_image_batch=True, refine=True, refine_decimate_ratio=0.1, refine_remesh_size=0.02, refine_size=0.01,
refine_steps=[3000, 6000, 9000, 12000, 15000, 21000], refine_steps_ratio=[0.1, 0.2, 0.3, 0.4, 0.5, 0.7], scale=0.8, sdf=False, seed=0, ssaa=1, stage=1, tcnn=False, test=False, test_no_mesh=False, test_no_video=False,
texture_size=2048, train_split='train', trainable_density_grid=False, update_extra_interval=16, vis_pose=False, visibility_mask_dilation=5, wo_smooth=False, workspace='trial_syn_lego/')
NeRFNetwork(
  (encoder): GridEncoder: input_dim=3 num_levels=16 level_dim=1 resolution=16 -> 2048 per_level_scale=1.3819 params=(6119864, 1) gridtype=hash align_corners=False interpolation=linear
  (sigma_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=19, out_features=32, bias=False)
      (1): Linear(in_features=32, out_features=1, bias=False)
    )
  )
  (encoder_color): GridEncoder: input_dim=3 num_levels=16 level_dim=2 resolution=16 -> 2048 per_level_scale=1.3819 params=(6119864, 2) gridtype=hash align_corners=False interpolation=linear
  (color_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=35, out_features=64, bias=False)
      (1): Linear(in_features=64, out_features=64, bias=False)
      (2): Linear(in_features=64, out_features=6, bias=False)
    )
  )
  (specular_net): MLP(
    (net): ModuleList(
      (0): Linear(in_features=6, out_features=32, bias=False)
      (1): Linear(in_features=32, out_features=3, bias=False)
    )
  )
)
[INFO] Loading stage 0 model to init stage 1 ...
[INFO] loaded model.
[WARN] missing keys: ['vertices_offsets']
[INFO] Loading latest checkpoint ...
[WARN] No checkpoint found, abort loading latest model.
Loading val data: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:01<00:00, 59.67it/s]
[mark untrained grid] 0 from 2097152
==> Start Training Epoch 1, lr=0.000001 ...
  0% 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "main.py", line 243, in <module>
    trainer.train(train_loader, valid_loader, max_epoch)
  File "/mnt/c/Users/jurre/Desktop/School/Minor/NeRF/nerf2mesh/nerf/utils.py", line 931, in train
    self.train_one_epoch(train_loader)
  File "/mnt/c/Users/jurre/Desktop/School/Minor/NeRF/nerf2mesh/nerf/utils.py", line 1164, in train_one_epoch
    preds, truths, loss_net = self.train_step(data)
  File "/mnt/c/Users/jurre/Desktop/School/Minor/NeRF/nerf2mesh/nerf/utils.py", line 720, in train_step
    self.model.update_triangles_errors(loss.detach())
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/c/Users/jurre/Desktop/School/Minor/NeRF/nerf2mesh/nerf/renderer.py", line 859, in update_triangles_errors
    TORCH_SCATTER.scatter_add(values, indices, out=self.triangles_errors)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch_scatter/scatter.py", line 29, in scatter_add
    return scatter_sum(src, index, dim, out, dim_size)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch_scatter/scatter.py", line 23, in scatter_sum
    return out.scatter_add_(dim, index, src)
RuntimeError: scatter(): Expected dtype int64 for index
  0% 0/100 [00:00<?, ?it/s]```

Did I misunderstood how to disable the ssaa? Since the parameter is "super-sampling anti-alias ratio", I figured a ratio of 1 would "disable" it. 


Thanks for all the help btw! Really appreciate it :)

**Comment by jurrejelle** [comment]
Alright, good to know I'm calling the right thing at least. With that out of the way, I did some more investigating, and printing it gives
```
tensor([298238., 298238., 296039.,  ...,   3012.,   3012.,   3011.],
       device='cuda:0')
```

Looking into the file, it seems like this might be causing it (renderer L815)

```py
        # ssaa
        if self.opt.ssaa > 1:
            image = scale_img_hwc(image, (h0, w0))
            depth = scale_img_hwc(depth, (h0, w0))
            T = scale_img_hwc(T, (h0, w0))
            trig_id = scale_img_hw(trig_id.float(), (h0, w0), mag='nearest', min='nearest').long()
        
            
        self.triangles_errors_id = trig_id
        ```
        
        
I replaced it with
```py
        if self.opt.ssaa > 1:
            image = scale_img_hwc(image, (h0, w0))
            depth = scale_img_hwc(depth, (h0, w0))
            T = scale_img_hwc(T, (h0, w0))
            trig_id = scale_img_hw(trig_id.float(), (h0, w0), mag='nearest', min='nearest').long()
        else:
            trid_id = trig_id.long()
            
        self.triangles_errors_id = trig_id
```, but that didn't seem to fix it. Since calling .long() on a tensor of type long doesn't change anything (I assume, I've never worked with tensors before) I replaced

```py


        indices = indices[mask].contiguous().long()
```
on line ~852 with 
```
        indices = indices[mask].contiguous().long()
```
That did seem to work.
I'm still curious why the tensor wasn't of type long initially though. I can't try running the original, OpenGL using code myself for now, but I think it would produce the same error if you said "--ssaa 1" on there, which might be worth looking into.

**Comment by ashawkey** [comment]
Thanks for the summary! I have fixed these bugs.
