### ISSUE TITLE
IndexError while refine_and_decimate

### ISSUE THREAD

**Issue by gr3atchoi** [ashawkey/nerf2mesh#44]
Thanks for your great work. 

while traning stage 1, 
`IndexError: boolean index did not match indexed array along dimension 0; dimension is 449875 but corresponding boolean dimension is 300000`
in   `File "nerf/renderer.py", line 222, in refine_and_decimate.`

I think the length of cnt_mask and mask is different because of the  the code block '# only care about the inner mesh'
```
            cnt = self.triangles_errors_cnt.cpu().numpy()
            cnt_mask = cnt > 0
            errors[cnt_mask] = errors[cnt_mask] / cnt[cnt_mask]

            # only care about the inner mesh
            errors = errors[:self.f_cumsum[1]]
            cnt_mask = cnt_mask[:self.f_cumsum[1]]

            # find a threshold to decide whether we perform subdivision / decimation.
            thresh_refine = np.percentile(errors[cnt_mask], 90)
            thresh_decimate = np.percentile(errors[cnt_mask], 50)

            mask[(errors > thresh_refine) & cnt_mask] = 2
            mask[(errors < thresh_decimate) & cnt_mask] = 1

            print(f'[INFO] faces to decimate {(mask == 1).sum()}, faces to refine {(mask == 2).sum()}')
```

**Comment by gr3atchoi** [comment]
FYI, my environment is 
nvidia/cuda:11.8.0-devel-ubuntu22.04. 
(My 4090 isn't working well with CUDA 11.6)
 Others are fine so far.

**Comment by ashawkey** [comment]
@gr3atchoi Sorry for the bug, I have fixed it in the latest commit!

**Comment by Gary-Qinghua** [comment]
I have a similar issue in refine_and_decimate.
The command of stage 1 like this:
CUDA_VISIBLE_DEVICES=4 python main.py ./data/room/ --workspace trial_sdf_360_room -O --data_format colmap --bound 8 --enable_cam_center --enable_cam_near_far --scale 0.2 --downscale 4 --stage 1 --iters 10000 --lambda_lap 1e-3 --lambda_normal 1e-3 --sdf

The error:
Traceback (most recent call last):
  File "main.py", line 243, in <module>
    trainer.train(train_loader, valid_loader, max_epoch)
  File "/home/zhangl/project/nerf2mesh-main/nerf/utils.py", line 931, in train
    self.train_one_epoch(train_loader)
  File "/home/zhangl/project/nerf2mesh-main/nerf/utils.py", line 1206, in train_one_epoch
    self.model.refine_and_decimate()
  File "/home/zhangl/miniconda3/envs/nerf2mesh/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/zhangl/project/nerf2mesh-main/nerf/renderer.py", line 252, in refine_and_decimate
    cur_v, cur_f = decimate_and_refine_mesh(cur_v, cur_f, mask, decimate_ratio=self.opt.refine_decimate_ratio, refine_size=self.opt.refine_size, refine_remesh_size=self.opt.refine_remesh_size)
  File "/home/zhangl/project/nerf2mesh-main/meshutils.py", line 199, in decimate_and_refine_mesh
    m = pml.Mesh(verts, faces, f_scalar_array=mask)
pymeshlab.pmeshlab.PyMeshLabException: Error while creating mesh: the number of face quality values is different from the number of faces.

**Comment by ashawkey** [comment]
@Gary-Qinghua Hi, `bound > 1` is not supported for sdf mode currently.

**Comment by Gary-Qinghua** [comment]
Thanks.
This command is in your scripts/runall_360_indoor_sdf.sh
