### ISSUE TITLE
about  AssertionError: sphere init is only for sdf mode!

### ISSUE THREAD

**Issue by Seiano** [ashawkey/nerf2mesh#60]
[INFO] Loading latest checkpoint ...
[WARN] No checkpoint found, abort loading latest model.
Traceback (most recent call last):
  File "main.py", line 241, in <module>
    trainer = Trainer('ngp', opt, model, device=device, workspace=opt.workspace, optimizer=optimizer, criterion=criterion, ema_decay=0.95 if opt.stage == 0 else None, fp16=opt.fp16, lr_scheduler=scheduler, scheduler_update_every_step=True, use_checkpoint=opt.ckpt, eval_interval=eval_interval, save_interval=save_interval)
  File "/workspace/nerf2mesh/nerf/utils.py", line 597, in __init__
    self.load_checkpoint()
  File "/workspace/nerf2mesh/nerf/utils.py", line 1418, in load_checkpoint
    self.model.init_double_sphere()
  File "/workspace/nerf2mesh/nerf/network.py", line 112, in init_double_sphere
    assert self.opt.sdf, 'sphere init is only for sdf mode!'
AssertionError: sphere init is only for sdf mode!

**Comment by ashawkey** [comment]
@Seiano Thanks for reporting the bug!
