### ISSUE TITLE
error:GLIBC

### ISSUE THREAD

**Issue by fanzz1208** [ashawkey/nerf2mesh#65]
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from nerf.gui import NeRFGUI
  File "/workspace/nerf2mesh/nerf/gui.py", line 4, in <module>
    import dearpygui.dearpygui as dpg
  File "/opt/conda/envs/ngp_pl/lib/python3.8/site-packages/dearpygui/dearpygui.py", line 22, in <module>
    import dearpygui._dearpygui as internal_dpg
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/conda/envs/ngp_pl/lib/python3.8/site-packages/dearpygui/_dearpygui.so)

**Comment by shenggedeqiang** [comment]
same question

**Comment by JQJ001** [comment]
I commented 'from nerf.gui import NeRFGUI' in File "main.py", line 4, then I can train normally.
