### ISSUE TITLE
error in run llff dataset

### ISSUE THREAD

**Issue by ruijie777** [ashawkey/nerf2mesh#68]
when run  CUDA_VISIBLE_DEVICES=6 python main.py data/nerf_llff_data/fern --workspace trial_llff_fern -O --data_format colmap --bound 4 --downscale 4 --stage 0 --visibility_mask_dilation 50
get error: 
[INFO] ColmapDataset: image H = 756, W = 1008
[INFO] 0 image exists in all 20 colmap entries.
Traceback (most recent call last):
  File "/media/ren3/disk1_ssd/ruijie/nerf2mesh-main/main.py", line 224, in <module>
    train_loader = NeRFDataset(opt, device=device, type=opt.train_split).dataloader()
  File "/media/ren3/disk1_ssd/ruijie/nerf2mesh-main/nerf/colmap_provider.py", line 182, in __init__
    self.intrinsics = torch.from_numpy(np.stack(intrinsics)) # [N, 4]
  File "<__array_function__ internals>", line 180, in stack
  File "/home/ren3/miniconda3/envs/nerf2mesh/lib/python3.9/site-packages/numpy/core/shape_base.py", line 422, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by whateverforever** [comment]
same error with custom dataset

**Comment by JQJ001** [comment]
The names of images in 'fern/images_4' does not match the names saved in 'images.bin', such as 'image000.png' v.s. 'IMG_4026.JPG'.
After renaming 'image000.png' to 'IMG_4026.JPG', the code can train normally.
