### ISSUE TITLE
Stage 2 running failed

### ISSUE THREAD

**Issue by Ethan-Zhu-code** [ashawkey/nerf2mesh#8]
Hi, thanks you for sharing your great work.

I am training on custom dataset following the command line with the exact same parameters:
`python main.py data/custom/ --workspace trial_custom -O --data_format colmap --bound 4 --scale 0.3 --stage 0 --clean_min_f 16 --clean_min_d 10 --lambda_tv 2e-8 --visibility_mask_dilation 50`

After the stage 0 training finished, I got two meshes: `mesh_0.ply` and `mesh_1.ply`. Then I used the second command line to train for stage 1：
`python main.py data/custom/ --workspace trial_custom -O --data_format colmap --bound 4 --scale 0.3 --stage 1 --iters 10000 --lambda_normal 1e-3`

However, exception occurred while the nerfrenderer try reading cascade meshes, which is shown as below:
`Traceback (most recent call last):
  File "/media/ethan/Files/nerf2mesh/main.py", line 159, in <module>
    model = NeRFNetwork(opt)
  File "/media/ethan/Files/nerf2mesh/nerf/network.py", line 38, in __init__
    super().__init__(opt)
  File "/media/ethan/Files/nerf2mesh/nerf/renderer.py", line 121, in __init__
    mesh = trimesh.load(os.path.join(self.opt.workspace, 'mesh_stage0', f'mesh_{cas}.ply'), force='mesh', skip_material=True, process=False)
  File "/home/ethan/anaconda3/envs/nerf2mesh/lib/python3.9/site-packages/trimesh/exchange/load.py", line 116, in load
    ) = parse_file_args(file_obj=file_obj,
  File "/home/ethan/anaconda3/envs/nerf2mesh/lib/python3.9/site-packages/trimesh/exchange/load.py", line 630, in parse_file_args
    raise ValueError('string is not a file: {}'.format(file_obj))
ValueError: string is not a file: trial_custom/mesh_stage0/mesh_2.ply
`
![screenshot2](https://user-images.githubusercontent.com/51185278/224251864-d301bd11-a069-48ae-8968-b50a5d599148.png)

 It seems the number of meshes the nerfrenderer tries to read is related to `--bound`, is it something wrong with my training data, or should I change the parameter for stage 1 training?

**Comment by Ethan-Zhu-code** [comment]
By the way, here is the visualization result of bound and poses when training on my custom dataset, with
`--bound 4 --scale 0.3`:

![screenshot3](https://user-images.githubusercontent.com/51185278/224257074-2449c75a-1143-48b8-b640-13e758350de2.png)

Should I change the parameters? Thanks.

**Comment by ashawkey** [comment]
@Ethan-Zhu-code Hi, I guess there should be some error message in stage0 exporting mesh? At bound 4 there should be three meshes (mesh_0, mesh_1, mesh_2.ply) exported.

**Comment by Ethan-Zhu-code** [comment]
> @Ethan-Zhu-code Hi, I guess there should be some error message in stage0 exporting mesh? At bound 4 there should be three meshes (mesh_0, mesh_1, mesh_2.ply) exported.

Thank you for the reply!

Yes, It seems all the vertices are removed when exporting mesh at cascade 2.
![screenshot4](https://user-images.githubusercontent.com/51185278/224270518-0fc88e97-90d5-4c1b-8131-7f8c5b938693.png)

The export meshes result are showed below, `mesh_0` seems reasonable, while `mesh_1` does not.

[mesh_0]
![1](https://user-images.githubusercontent.com/51185278/224276562-0980e766-b946-4b76-b62b-fc4f52e3fd55.png)

[mesh_1]
![2](https://user-images.githubusercontent.com/51185278/224276708-cd4c7d12-9aa0-48e9-9bf0-10752bbb928c.png)

Is this related to my scale and bound setting? Any advice on how to fix the issue is appreciated.

**Comment by ashawkey** [comment]
In that case you can just reduce bound to 1, as there's almost nothing outside [-1, 1]^3.
