### ISSUE TITLE
build raymarching error: python setup.py build_ext --inplace

### ISSUE THREAD

**Issue by MisssThe** [ashawkey/nerf2mesh#80]
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\torch\utils\cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Project\Python\nerf2mesh\raymarching\setup.py", line 44, in <module>
    setup(
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\torch\utils\cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\torch\utils\cpp_extension.py", line 738, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\torch\utils\cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by MisssThe** [comment]
when I use cuda 11.3 I can build this success,but compile torch-cuda-nn failed.

**Comment by MisssThe** [comment]
2 errors detected in the compilation of "D:/Project/Python/nerf2mesh/raymarching/src/raymarching.cu".
raymarching.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\torch\utils\cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Project\Python\nerf2mesh\raymarching\setup.py", line 44, in <module>
    setup(
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\torch\utils\cpp_extension.py", line 765, in build_extensions
    build_ext.build_extensions(self)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\command\build_ext.py", line 246, in build_extension
    _build_ext.build_extension(self, ext)
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 548, in build_extension
    objects = self.compiler.compile(
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\torch\utils\cpp_extension.py", line 738, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\torch\utils\cpp_extension.py", line 1487, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "D:\Application\Anaconda\envs\nerf22mesh\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

**Comment by MisssThe** [comment]
window+cuda11.6+pytorch11.2+visual studio2019 16.9.26

**Comment by SavageChigga** [comment]
I had the same problem
windows11+cuda11.6+pytorch1.12.1+visual studio2019 failed
windows11+cuda11.3+pytorch1.11+visual studio2019 failed
windows11+cuda11.6+pytorch1.12.1+visual studio2022 failed
windows11+cuda11.3+pytorch1.11+visual studio2022 failed
ubuntu22+cuda11.6+pytorch12.0 failed

**Comment by ptjzh4869** [comment]
use
cmdclass={'build_ext': BuildExtension.with_options(use_ninja=False),}
to replace 
cmdclass={"build_ext": BuildExtension,}

in setup.py

hope this will help you to install raymarching
